Repository bsv-blockchain/block-headers-service, pull requests merged in 2023-04, with the labels that each got.

#88 Fix http endpoints
  cmd/main.go
  data/sql/headers.go
  domains/headers.go
  internal/tests/testrepository/header_testrepository.go
  repository/dto/headers.go
  repository/header_repository.go
  service/service.go
  transports/http/handlers/headers_handler.go
  transports/http/handlers/tip_handler.go
  transports/http/headers.go
  transports/http/server/http_server.go
  vconfig/config.go
  vconfig/viper.go
Labels: bug, bug-P3

#89 Add tests for header service
  internal/tests/testrepository/header_testrepository.go
  internal/tests/testrepository/mock_header.go
  internal/tests/testrepository/test_repository.go
  service/chain_service_test.go
  service/header_service.go
  service/header_service_test.go
  service/service.go
Labels: test

#98 fix(#86): docker entrypoint was calling wrong binary name to run application
  .goreleaser-darwin.yml
  .goreleaser-linux.yml
  entrypoint.sh
Labels: bug-P3

#95 Confirmation number was off by one
  data/sql/headers.go
Labels: bug, bug-P3

#104 Format tips endpoint response
  data/sql/headers.go
  domains/headers.go
  internal/tests/testrepository/header_testrepository.go
  repository/header_repository.go
  repository/repository.go
  service/header_service.go
  service/service.go
  transports/http/handlers/headers_handler.go
  transports/http/handlers/tip_handler.go
  transports/http/headers.go
Labels: enhancement, bug-P3

#106 Add authorization for http server
  README.md
  cmd/main.go
  data/sql/migrations/4_create_tokens_table.up.sql
  data/sql/tokens.go
  docker-compose.yml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domains/headers.go
  domains/tokens.go
  go.mod
  go.sum
  internal/tests/testrepository/token_testrepository.go
  repository/dto/tokens.go
  repository/repository.go
  repository/token_repository.go
  service/service.go
  service/token_service.go
  transports/http/handlers/bearer_middleware.go
  transports/http/handlers/handler.go
  transports/http/handlers/headers_handler.go
  transports/http/handlers/network_handler.go
  transports/http/handlers/tip_handler.go
  transports/http/handlers/tokens_handler.go
  transports/http/handlers/tokens_handler_test.go
  transports/http/headers.go
  vconfig/config.go
  vconfig/viper.go
Labels: enhancement, feature
