Repository bsv-blockchain/block-headers-service, pull requests merged in 2024-02, with the labels that each got.

#193 fix(BUX-533): refine the order of initializing the database and checking for t…
  config/config.go
Labels: bug

#192 fix(BUX-550): replace wrong character ? in delete methods to make it work with postgres
  database/sql/tokens.go
  database/sql/webhooks.go
Labels: bug

#205 feat(BUX-000): logger fix for kibana
  logging/logging.go
Labels: enhancement, tested

#191 Release Candidate v1.1.0
  cmd/main.go
  config.example.yaml
  config/config.go
  config/defaults.go
  go.mod
  metrics/gin_middleware.go
  metrics/global.go
  metrics/latest_block.go
  metrics/metrics.go
  metrics/naming.go
  metrics/request.go
  metrics/vec.go
  service/chain_service.go
Labels: tested

#209 feat(#208): readme update
  README.md
Labels: tested
