Repository bsv-blockchain/block-headers-service, pull requests merged in 2024-08, with the labels that each got.

#266 deps: update dependencies
  go.mod
  go.sum
Labels: tested, regression-tests

#268 chore(deps): bump github.com/centrifugal/centrifuge from 0.33.0 to 0.…
  go.mod
  go.sum
Labels: deps, tested, regression-tests

#270 ci(SPV-992): add sync labels workflow
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: ci, tested

#271 ci(SPV-992): use dependabot update groups
  .github/dependabot.yml
Labels: tested
