Repository bsv-blockchain/block-headers-service, pull requests merged in 2024-05, with the labels that each got.

#244 feat(SPV-760): handle insertion of genesis block for chosen chain net during db migration
  cmd/main.go
  config/config.go
  config/defaults.go
  config/p2p_network_params.go
  database/database.go
  database/genesis.go
  domains/headers.go
  internal/tests/fixtures/chain_fixtures.go
  internal/tests/testapp/test_bhs.go
  internal/transports/p2p/server.go
  service/header_service.go
  service/service.go
  transports/http/endpoints/api/headers/header_endpoints_test.go
  transports/p2p/server.go
Labels: tested

#246 fix(SPV-769): check sql.select result length
  database/sql/headers.go
Labels: bug, tested

#253 feat(SPV-XXX):update dependencies
  go.mod
  go.sum
Labels: feature, tested, regression-tests

#252 feat(SPV-748): add response to getHeaders
  database/repository/header_repository.go
  database/sql/headers.go
  internal/tests/fixtures/blockheader_util.go
  internal/tests/testrepository/header_testrepository.go
  internal/transports/p2p/peer/peer.go
  repository/repository.go
  service/header_service.go
  service/header_service_test.go
  service/service.go
Labels: tested, regression-tests
